language: node_js

node_js:
  - '13'

env:
  global:
    secure: ZUnK3J9J4Y2avSEiKfUWBSYBJN7Z9Fta/Ipf5LEc6yamPbwl3uYZgHf1kGHjzyWoPwUnFwKXmaO+L4MB/K+Q3pZi72jyBxS6WcPj7O2S8BWE2nLRN429YbP/Gegtx4VWS1ecw1Swczx4couvQo8RJakqBoMrWsTiGmB0Rj8JKIUWQopfqd+eMlnSha8Ce7GI16LLbmKt9jNj2LtZTaoib0Xz8bUprV7Sa6GNRxAHIc29YR9r9N3ORA0BgvrDv5DdRdCJUx73aRBSelqko5yJ3YPgPHfssmGbiZ53UVEgKsS5ECjqaTNCvp+no6jLjuYhPSuTjeeDIz3a1P2JL2Cz3mWhQW4yOuXaAOzLxAmaW1pVlVTNxQWA+7KGIsiiTSqea1H6JAYrBjXUmivQ3QoPm5utWQBuT/9v73Wmiex4BQa16ZXAbw01YP+MjyoL+JMWrA6d0ac2+0Tn4Dm3ac2tuqTEf0Y4HFMHUhyH9/XLOSbRr5oOrWfUQ8Wbyme/ZKn5Sx006yYkSpsCPgPvSWDnpgyYztOy1GEB+x0jke/pdNPN2lv6HV6QNzSHPe9vMBvqgI40DHskFJ7tGRW4G7cKuo4G5x/aPZV691nOdMQNOT2N+ZKNHJ90UzuSxabOz3bcpVA1vYToXdVPlGMQkPOazqFNe6Bfy2GlRvhvFJG8fcg=

after_success: npm run coverage
